//
// Generated by Bluespec Compiler, version 2023.07 (build 0eb551d)
//
// On Fri Feb 23 16:46:49 CET 2024
//
//
// Ports:
// Name                         I/O  size props
// naiveShfl                      O   256
// naiveShfl_in                   I   256
// naiveShfl_shftAmnt             I     4
//
// Combinational paths from inputs to outputs:
//   (naiveShfl_in, naiveShfl_shftAmnt) -> naiveShfl
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_naiveShfl(naiveShfl_in,
			naiveShfl_shftAmnt,
			naiveShfl);
  // value method naiveShfl
  input  [255 : 0] naiveShfl_in;
  input  [3 : 0] naiveShfl_shftAmnt;
  output [255 : 0] naiveShfl;

  // signals for module outputs
  wire [255 : 0] naiveShfl;

  // remaining internal signals
  reg [15 : 0] CASE_naiveShfl_shftAmnt_0_naiveShfl_in_BITS_15_ETC__q16,
	       CASE_x062_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q6,
	       CASE_x128_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q7,
	       CASE_x194_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q8,
	       CASE_x260_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q9,
	       CASE_x326_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q10,
	       CASE_x392_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q11,
	       CASE_x396_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q1,
	       CASE_x458_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q12,
	       CASE_x524_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q13,
	       CASE_x590_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q14,
	       CASE_x656_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q15,
	       CASE_x798_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q2,
	       CASE_x864_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q3,
	       CASE_x930_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q4,
	       CASE_x996_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q5;
  wire [223 : 0] SEL_ARR_naiveShfl_in_BITS_15_TO_0_naiveShfl_in_ETC___d52;
  wire [191 : 0] SEL_ARR_naiveShfl_in_BITS_15_TO_0_naiveShfl_in_ETC___d47;
  wire [159 : 0] SEL_ARR_naiveShfl_in_BITS_15_TO_0_naiveShfl_in_ETC___d42;
  wire [127 : 0] SEL_ARR_naiveShfl_in_BITS_15_TO_0_naiveShfl_in_ETC___d37;
  wire [95 : 0] SEL_ARR_naiveShfl_in_BITS_15_TO_0_naiveShfl_in_ETC___d32;
  wire [63 : 0] SEL_ARR_naiveShfl_in_BITS_15_TO_0_naiveShfl_in_ETC___d27;
  wire [31 : 0] SEL_ARR_naiveShfl_in_BITS_15_TO_0_naiveShfl_in_ETC___d22;
  wire [3 : 0] x__h1396,
	       x__h1798,
	       x__h1864,
	       x__h1930,
	       x__h1996,
	       x__h2062,
	       x__h2128,
	       x__h2194,
	       x__h2260,
	       x__h2326,
	       x__h2392,
	       x__h2458,
	       x__h2524,
	       x__h2590,
	       x__h2656;

  // value method naiveShfl
  assign naiveShfl =
	     { SEL_ARR_naiveShfl_in_BITS_15_TO_0_naiveShfl_in_ETC___d52,
	       CASE_x656_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q15,
	       CASE_naiveShfl_shftAmnt_0_naiveShfl_in_BITS_15_ETC__q16 } ;

  // remaining internal signals
  assign SEL_ARR_naiveShfl_in_BITS_15_TO_0_naiveShfl_in_ETC___d22 =
	     { CASE_x396_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q1,
	       CASE_x798_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q2 } ;
  assign SEL_ARR_naiveShfl_in_BITS_15_TO_0_naiveShfl_in_ETC___d27 =
	     { SEL_ARR_naiveShfl_in_BITS_15_TO_0_naiveShfl_in_ETC___d22,
	       CASE_x864_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q3,
	       CASE_x930_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q4 } ;
  assign SEL_ARR_naiveShfl_in_BITS_15_TO_0_naiveShfl_in_ETC___d32 =
	     { SEL_ARR_naiveShfl_in_BITS_15_TO_0_naiveShfl_in_ETC___d27,
	       CASE_x996_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q5,
	       CASE_x062_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q6 } ;
  assign SEL_ARR_naiveShfl_in_BITS_15_TO_0_naiveShfl_in_ETC___d37 =
	     { SEL_ARR_naiveShfl_in_BITS_15_TO_0_naiveShfl_in_ETC___d32,
	       CASE_x128_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q7,
	       CASE_x194_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q8 } ;
  assign SEL_ARR_naiveShfl_in_BITS_15_TO_0_naiveShfl_in_ETC___d42 =
	     { SEL_ARR_naiveShfl_in_BITS_15_TO_0_naiveShfl_in_ETC___d37,
	       CASE_x260_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q9,
	       CASE_x326_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q10 } ;
  assign SEL_ARR_naiveShfl_in_BITS_15_TO_0_naiveShfl_in_ETC___d47 =
	     { SEL_ARR_naiveShfl_in_BITS_15_TO_0_naiveShfl_in_ETC___d42,
	       CASE_x392_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q11,
	       CASE_x458_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q12 } ;
  assign SEL_ARR_naiveShfl_in_BITS_15_TO_0_naiveShfl_in_ETC___d52 =
	     { SEL_ARR_naiveShfl_in_BITS_15_TO_0_naiveShfl_in_ETC___d47,
	       CASE_x524_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q13,
	       CASE_x590_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q14 } ;
  assign x__h1396 = naiveShfl_shftAmnt + 4'd15 ;
  assign x__h1798 = naiveShfl_shftAmnt + 4'd14 ;
  assign x__h1864 = naiveShfl_shftAmnt + 4'd13 ;
  assign x__h1930 = naiveShfl_shftAmnt + 4'd12 ;
  assign x__h1996 = naiveShfl_shftAmnt + 4'd11 ;
  assign x__h2062 = naiveShfl_shftAmnt + 4'd10 ;
  assign x__h2128 = naiveShfl_shftAmnt + 4'd9 ;
  assign x__h2194 = naiveShfl_shftAmnt + 4'd8 ;
  assign x__h2260 = naiveShfl_shftAmnt + 4'd7 ;
  assign x__h2326 = naiveShfl_shftAmnt + 4'd6 ;
  assign x__h2392 = naiveShfl_shftAmnt + 4'd5 ;
  assign x__h2458 = naiveShfl_shftAmnt + 4'd4 ;
  assign x__h2524 = naiveShfl_shftAmnt + 4'd3 ;
  assign x__h2590 = naiveShfl_shftAmnt + 4'd2 ;
  assign x__h2656 = naiveShfl_shftAmnt + 4'd1 ;
  always@(x__h1396 or naiveShfl_in)
  begin
    case (x__h1396)
      4'd0:
	  CASE_x396_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q1 =
	      naiveShfl_in[15:0];
      4'd1:
	  CASE_x396_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q1 =
	      naiveShfl_in[31:16];
      4'd2:
	  CASE_x396_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q1 =
	      naiveShfl_in[47:32];
      4'd3:
	  CASE_x396_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q1 =
	      naiveShfl_in[63:48];
      4'd4:
	  CASE_x396_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q1 =
	      naiveShfl_in[79:64];
      4'd5:
	  CASE_x396_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q1 =
	      naiveShfl_in[95:80];
      4'd6:
	  CASE_x396_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q1 =
	      naiveShfl_in[111:96];
      4'd7:
	  CASE_x396_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q1 =
	      naiveShfl_in[127:112];
      4'd8:
	  CASE_x396_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q1 =
	      naiveShfl_in[143:128];
      4'd9:
	  CASE_x396_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q1 =
	      naiveShfl_in[159:144];
      4'd10:
	  CASE_x396_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q1 =
	      naiveShfl_in[175:160];
      4'd11:
	  CASE_x396_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q1 =
	      naiveShfl_in[191:176];
      4'd12:
	  CASE_x396_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q1 =
	      naiveShfl_in[207:192];
      4'd13:
	  CASE_x396_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q1 =
	      naiveShfl_in[223:208];
      4'd14:
	  CASE_x396_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q1 =
	      naiveShfl_in[239:224];
      4'd15:
	  CASE_x396_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q1 =
	      naiveShfl_in[255:240];
    endcase
  end
  always@(x__h1798 or naiveShfl_in)
  begin
    case (x__h1798)
      4'd0:
	  CASE_x798_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q2 =
	      naiveShfl_in[15:0];
      4'd1:
	  CASE_x798_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q2 =
	      naiveShfl_in[31:16];
      4'd2:
	  CASE_x798_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q2 =
	      naiveShfl_in[47:32];
      4'd3:
	  CASE_x798_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q2 =
	      naiveShfl_in[63:48];
      4'd4:
	  CASE_x798_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q2 =
	      naiveShfl_in[79:64];
      4'd5:
	  CASE_x798_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q2 =
	      naiveShfl_in[95:80];
      4'd6:
	  CASE_x798_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q2 =
	      naiveShfl_in[111:96];
      4'd7:
	  CASE_x798_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q2 =
	      naiveShfl_in[127:112];
      4'd8:
	  CASE_x798_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q2 =
	      naiveShfl_in[143:128];
      4'd9:
	  CASE_x798_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q2 =
	      naiveShfl_in[159:144];
      4'd10:
	  CASE_x798_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q2 =
	      naiveShfl_in[175:160];
      4'd11:
	  CASE_x798_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q2 =
	      naiveShfl_in[191:176];
      4'd12:
	  CASE_x798_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q2 =
	      naiveShfl_in[207:192];
      4'd13:
	  CASE_x798_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q2 =
	      naiveShfl_in[223:208];
      4'd14:
	  CASE_x798_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q2 =
	      naiveShfl_in[239:224];
      4'd15:
	  CASE_x798_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q2 =
	      naiveShfl_in[255:240];
    endcase
  end
  always@(x__h1864 or naiveShfl_in)
  begin
    case (x__h1864)
      4'd0:
	  CASE_x864_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q3 =
	      naiveShfl_in[15:0];
      4'd1:
	  CASE_x864_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q3 =
	      naiveShfl_in[31:16];
      4'd2:
	  CASE_x864_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q3 =
	      naiveShfl_in[47:32];
      4'd3:
	  CASE_x864_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q3 =
	      naiveShfl_in[63:48];
      4'd4:
	  CASE_x864_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q3 =
	      naiveShfl_in[79:64];
      4'd5:
	  CASE_x864_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q3 =
	      naiveShfl_in[95:80];
      4'd6:
	  CASE_x864_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q3 =
	      naiveShfl_in[111:96];
      4'd7:
	  CASE_x864_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q3 =
	      naiveShfl_in[127:112];
      4'd8:
	  CASE_x864_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q3 =
	      naiveShfl_in[143:128];
      4'd9:
	  CASE_x864_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q3 =
	      naiveShfl_in[159:144];
      4'd10:
	  CASE_x864_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q3 =
	      naiveShfl_in[175:160];
      4'd11:
	  CASE_x864_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q3 =
	      naiveShfl_in[191:176];
      4'd12:
	  CASE_x864_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q3 =
	      naiveShfl_in[207:192];
      4'd13:
	  CASE_x864_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q3 =
	      naiveShfl_in[223:208];
      4'd14:
	  CASE_x864_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q3 =
	      naiveShfl_in[239:224];
      4'd15:
	  CASE_x864_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q3 =
	      naiveShfl_in[255:240];
    endcase
  end
  always@(x__h1930 or naiveShfl_in)
  begin
    case (x__h1930)
      4'd0:
	  CASE_x930_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q4 =
	      naiveShfl_in[15:0];
      4'd1:
	  CASE_x930_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q4 =
	      naiveShfl_in[31:16];
      4'd2:
	  CASE_x930_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q4 =
	      naiveShfl_in[47:32];
      4'd3:
	  CASE_x930_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q4 =
	      naiveShfl_in[63:48];
      4'd4:
	  CASE_x930_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q4 =
	      naiveShfl_in[79:64];
      4'd5:
	  CASE_x930_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q4 =
	      naiveShfl_in[95:80];
      4'd6:
	  CASE_x930_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q4 =
	      naiveShfl_in[111:96];
      4'd7:
	  CASE_x930_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q4 =
	      naiveShfl_in[127:112];
      4'd8:
	  CASE_x930_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q4 =
	      naiveShfl_in[143:128];
      4'd9:
	  CASE_x930_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q4 =
	      naiveShfl_in[159:144];
      4'd10:
	  CASE_x930_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q4 =
	      naiveShfl_in[175:160];
      4'd11:
	  CASE_x930_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q4 =
	      naiveShfl_in[191:176];
      4'd12:
	  CASE_x930_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q4 =
	      naiveShfl_in[207:192];
      4'd13:
	  CASE_x930_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q4 =
	      naiveShfl_in[223:208];
      4'd14:
	  CASE_x930_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q4 =
	      naiveShfl_in[239:224];
      4'd15:
	  CASE_x930_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q4 =
	      naiveShfl_in[255:240];
    endcase
  end
  always@(x__h1996 or naiveShfl_in)
  begin
    case (x__h1996)
      4'd0:
	  CASE_x996_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q5 =
	      naiveShfl_in[15:0];
      4'd1:
	  CASE_x996_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q5 =
	      naiveShfl_in[31:16];
      4'd2:
	  CASE_x996_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q5 =
	      naiveShfl_in[47:32];
      4'd3:
	  CASE_x996_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q5 =
	      naiveShfl_in[63:48];
      4'd4:
	  CASE_x996_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q5 =
	      naiveShfl_in[79:64];
      4'd5:
	  CASE_x996_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q5 =
	      naiveShfl_in[95:80];
      4'd6:
	  CASE_x996_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q5 =
	      naiveShfl_in[111:96];
      4'd7:
	  CASE_x996_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q5 =
	      naiveShfl_in[127:112];
      4'd8:
	  CASE_x996_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q5 =
	      naiveShfl_in[143:128];
      4'd9:
	  CASE_x996_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q5 =
	      naiveShfl_in[159:144];
      4'd10:
	  CASE_x996_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q5 =
	      naiveShfl_in[175:160];
      4'd11:
	  CASE_x996_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q5 =
	      naiveShfl_in[191:176];
      4'd12:
	  CASE_x996_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q5 =
	      naiveShfl_in[207:192];
      4'd13:
	  CASE_x996_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q5 =
	      naiveShfl_in[223:208];
      4'd14:
	  CASE_x996_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q5 =
	      naiveShfl_in[239:224];
      4'd15:
	  CASE_x996_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q5 =
	      naiveShfl_in[255:240];
    endcase
  end
  always@(x__h2062 or naiveShfl_in)
  begin
    case (x__h2062)
      4'd0:
	  CASE_x062_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q6 =
	      naiveShfl_in[15:0];
      4'd1:
	  CASE_x062_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q6 =
	      naiveShfl_in[31:16];
      4'd2:
	  CASE_x062_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q6 =
	      naiveShfl_in[47:32];
      4'd3:
	  CASE_x062_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q6 =
	      naiveShfl_in[63:48];
      4'd4:
	  CASE_x062_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q6 =
	      naiveShfl_in[79:64];
      4'd5:
	  CASE_x062_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q6 =
	      naiveShfl_in[95:80];
      4'd6:
	  CASE_x062_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q6 =
	      naiveShfl_in[111:96];
      4'd7:
	  CASE_x062_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q6 =
	      naiveShfl_in[127:112];
      4'd8:
	  CASE_x062_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q6 =
	      naiveShfl_in[143:128];
      4'd9:
	  CASE_x062_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q6 =
	      naiveShfl_in[159:144];
      4'd10:
	  CASE_x062_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q6 =
	      naiveShfl_in[175:160];
      4'd11:
	  CASE_x062_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q6 =
	      naiveShfl_in[191:176];
      4'd12:
	  CASE_x062_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q6 =
	      naiveShfl_in[207:192];
      4'd13:
	  CASE_x062_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q6 =
	      naiveShfl_in[223:208];
      4'd14:
	  CASE_x062_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q6 =
	      naiveShfl_in[239:224];
      4'd15:
	  CASE_x062_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q6 =
	      naiveShfl_in[255:240];
    endcase
  end
  always@(x__h2128 or naiveShfl_in)
  begin
    case (x__h2128)
      4'd0:
	  CASE_x128_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q7 =
	      naiveShfl_in[15:0];
      4'd1:
	  CASE_x128_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q7 =
	      naiveShfl_in[31:16];
      4'd2:
	  CASE_x128_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q7 =
	      naiveShfl_in[47:32];
      4'd3:
	  CASE_x128_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q7 =
	      naiveShfl_in[63:48];
      4'd4:
	  CASE_x128_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q7 =
	      naiveShfl_in[79:64];
      4'd5:
	  CASE_x128_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q7 =
	      naiveShfl_in[95:80];
      4'd6:
	  CASE_x128_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q7 =
	      naiveShfl_in[111:96];
      4'd7:
	  CASE_x128_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q7 =
	      naiveShfl_in[127:112];
      4'd8:
	  CASE_x128_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q7 =
	      naiveShfl_in[143:128];
      4'd9:
	  CASE_x128_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q7 =
	      naiveShfl_in[159:144];
      4'd10:
	  CASE_x128_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q7 =
	      naiveShfl_in[175:160];
      4'd11:
	  CASE_x128_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q7 =
	      naiveShfl_in[191:176];
      4'd12:
	  CASE_x128_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q7 =
	      naiveShfl_in[207:192];
      4'd13:
	  CASE_x128_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q7 =
	      naiveShfl_in[223:208];
      4'd14:
	  CASE_x128_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q7 =
	      naiveShfl_in[239:224];
      4'd15:
	  CASE_x128_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q7 =
	      naiveShfl_in[255:240];
    endcase
  end
  always@(x__h2194 or naiveShfl_in)
  begin
    case (x__h2194)
      4'd0:
	  CASE_x194_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q8 =
	      naiveShfl_in[15:0];
      4'd1:
	  CASE_x194_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q8 =
	      naiveShfl_in[31:16];
      4'd2:
	  CASE_x194_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q8 =
	      naiveShfl_in[47:32];
      4'd3:
	  CASE_x194_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q8 =
	      naiveShfl_in[63:48];
      4'd4:
	  CASE_x194_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q8 =
	      naiveShfl_in[79:64];
      4'd5:
	  CASE_x194_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q8 =
	      naiveShfl_in[95:80];
      4'd6:
	  CASE_x194_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q8 =
	      naiveShfl_in[111:96];
      4'd7:
	  CASE_x194_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q8 =
	      naiveShfl_in[127:112];
      4'd8:
	  CASE_x194_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q8 =
	      naiveShfl_in[143:128];
      4'd9:
	  CASE_x194_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q8 =
	      naiveShfl_in[159:144];
      4'd10:
	  CASE_x194_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q8 =
	      naiveShfl_in[175:160];
      4'd11:
	  CASE_x194_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q8 =
	      naiveShfl_in[191:176];
      4'd12:
	  CASE_x194_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q8 =
	      naiveShfl_in[207:192];
      4'd13:
	  CASE_x194_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q8 =
	      naiveShfl_in[223:208];
      4'd14:
	  CASE_x194_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q8 =
	      naiveShfl_in[239:224];
      4'd15:
	  CASE_x194_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q8 =
	      naiveShfl_in[255:240];
    endcase
  end
  always@(x__h2260 or naiveShfl_in)
  begin
    case (x__h2260)
      4'd0:
	  CASE_x260_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q9 =
	      naiveShfl_in[15:0];
      4'd1:
	  CASE_x260_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q9 =
	      naiveShfl_in[31:16];
      4'd2:
	  CASE_x260_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q9 =
	      naiveShfl_in[47:32];
      4'd3:
	  CASE_x260_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q9 =
	      naiveShfl_in[63:48];
      4'd4:
	  CASE_x260_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q9 =
	      naiveShfl_in[79:64];
      4'd5:
	  CASE_x260_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q9 =
	      naiveShfl_in[95:80];
      4'd6:
	  CASE_x260_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q9 =
	      naiveShfl_in[111:96];
      4'd7:
	  CASE_x260_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q9 =
	      naiveShfl_in[127:112];
      4'd8:
	  CASE_x260_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q9 =
	      naiveShfl_in[143:128];
      4'd9:
	  CASE_x260_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q9 =
	      naiveShfl_in[159:144];
      4'd10:
	  CASE_x260_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q9 =
	      naiveShfl_in[175:160];
      4'd11:
	  CASE_x260_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q9 =
	      naiveShfl_in[191:176];
      4'd12:
	  CASE_x260_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q9 =
	      naiveShfl_in[207:192];
      4'd13:
	  CASE_x260_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q9 =
	      naiveShfl_in[223:208];
      4'd14:
	  CASE_x260_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q9 =
	      naiveShfl_in[239:224];
      4'd15:
	  CASE_x260_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q9 =
	      naiveShfl_in[255:240];
    endcase
  end
  always@(x__h2326 or naiveShfl_in)
  begin
    case (x__h2326)
      4'd0:
	  CASE_x326_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q10 =
	      naiveShfl_in[15:0];
      4'd1:
	  CASE_x326_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q10 =
	      naiveShfl_in[31:16];
      4'd2:
	  CASE_x326_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q10 =
	      naiveShfl_in[47:32];
      4'd3:
	  CASE_x326_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q10 =
	      naiveShfl_in[63:48];
      4'd4:
	  CASE_x326_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q10 =
	      naiveShfl_in[79:64];
      4'd5:
	  CASE_x326_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q10 =
	      naiveShfl_in[95:80];
      4'd6:
	  CASE_x326_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q10 =
	      naiveShfl_in[111:96];
      4'd7:
	  CASE_x326_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q10 =
	      naiveShfl_in[127:112];
      4'd8:
	  CASE_x326_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q10 =
	      naiveShfl_in[143:128];
      4'd9:
	  CASE_x326_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q10 =
	      naiveShfl_in[159:144];
      4'd10:
	  CASE_x326_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q10 =
	      naiveShfl_in[175:160];
      4'd11:
	  CASE_x326_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q10 =
	      naiveShfl_in[191:176];
      4'd12:
	  CASE_x326_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q10 =
	      naiveShfl_in[207:192];
      4'd13:
	  CASE_x326_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q10 =
	      naiveShfl_in[223:208];
      4'd14:
	  CASE_x326_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q10 =
	      naiveShfl_in[239:224];
      4'd15:
	  CASE_x326_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q10 =
	      naiveShfl_in[255:240];
    endcase
  end
  always@(x__h2392 or naiveShfl_in)
  begin
    case (x__h2392)
      4'd0:
	  CASE_x392_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q11 =
	      naiveShfl_in[15:0];
      4'd1:
	  CASE_x392_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q11 =
	      naiveShfl_in[31:16];
      4'd2:
	  CASE_x392_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q11 =
	      naiveShfl_in[47:32];
      4'd3:
	  CASE_x392_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q11 =
	      naiveShfl_in[63:48];
      4'd4:
	  CASE_x392_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q11 =
	      naiveShfl_in[79:64];
      4'd5:
	  CASE_x392_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q11 =
	      naiveShfl_in[95:80];
      4'd6:
	  CASE_x392_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q11 =
	      naiveShfl_in[111:96];
      4'd7:
	  CASE_x392_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q11 =
	      naiveShfl_in[127:112];
      4'd8:
	  CASE_x392_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q11 =
	      naiveShfl_in[143:128];
      4'd9:
	  CASE_x392_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q11 =
	      naiveShfl_in[159:144];
      4'd10:
	  CASE_x392_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q11 =
	      naiveShfl_in[175:160];
      4'd11:
	  CASE_x392_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q11 =
	      naiveShfl_in[191:176];
      4'd12:
	  CASE_x392_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q11 =
	      naiveShfl_in[207:192];
      4'd13:
	  CASE_x392_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q11 =
	      naiveShfl_in[223:208];
      4'd14:
	  CASE_x392_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q11 =
	      naiveShfl_in[239:224];
      4'd15:
	  CASE_x392_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q11 =
	      naiveShfl_in[255:240];
    endcase
  end
  always@(x__h2458 or naiveShfl_in)
  begin
    case (x__h2458)
      4'd0:
	  CASE_x458_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q12 =
	      naiveShfl_in[15:0];
      4'd1:
	  CASE_x458_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q12 =
	      naiveShfl_in[31:16];
      4'd2:
	  CASE_x458_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q12 =
	      naiveShfl_in[47:32];
      4'd3:
	  CASE_x458_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q12 =
	      naiveShfl_in[63:48];
      4'd4:
	  CASE_x458_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q12 =
	      naiveShfl_in[79:64];
      4'd5:
	  CASE_x458_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q12 =
	      naiveShfl_in[95:80];
      4'd6:
	  CASE_x458_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q12 =
	      naiveShfl_in[111:96];
      4'd7:
	  CASE_x458_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q12 =
	      naiveShfl_in[127:112];
      4'd8:
	  CASE_x458_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q12 =
	      naiveShfl_in[143:128];
      4'd9:
	  CASE_x458_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q12 =
	      naiveShfl_in[159:144];
      4'd10:
	  CASE_x458_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q12 =
	      naiveShfl_in[175:160];
      4'd11:
	  CASE_x458_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q12 =
	      naiveShfl_in[191:176];
      4'd12:
	  CASE_x458_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q12 =
	      naiveShfl_in[207:192];
      4'd13:
	  CASE_x458_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q12 =
	      naiveShfl_in[223:208];
      4'd14:
	  CASE_x458_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q12 =
	      naiveShfl_in[239:224];
      4'd15:
	  CASE_x458_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q12 =
	      naiveShfl_in[255:240];
    endcase
  end
  always@(x__h2524 or naiveShfl_in)
  begin
    case (x__h2524)
      4'd0:
	  CASE_x524_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q13 =
	      naiveShfl_in[15:0];
      4'd1:
	  CASE_x524_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q13 =
	      naiveShfl_in[31:16];
      4'd2:
	  CASE_x524_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q13 =
	      naiveShfl_in[47:32];
      4'd3:
	  CASE_x524_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q13 =
	      naiveShfl_in[63:48];
      4'd4:
	  CASE_x524_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q13 =
	      naiveShfl_in[79:64];
      4'd5:
	  CASE_x524_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q13 =
	      naiveShfl_in[95:80];
      4'd6:
	  CASE_x524_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q13 =
	      naiveShfl_in[111:96];
      4'd7:
	  CASE_x524_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q13 =
	      naiveShfl_in[127:112];
      4'd8:
	  CASE_x524_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q13 =
	      naiveShfl_in[143:128];
      4'd9:
	  CASE_x524_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q13 =
	      naiveShfl_in[159:144];
      4'd10:
	  CASE_x524_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q13 =
	      naiveShfl_in[175:160];
      4'd11:
	  CASE_x524_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q13 =
	      naiveShfl_in[191:176];
      4'd12:
	  CASE_x524_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q13 =
	      naiveShfl_in[207:192];
      4'd13:
	  CASE_x524_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q13 =
	      naiveShfl_in[223:208];
      4'd14:
	  CASE_x524_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q13 =
	      naiveShfl_in[239:224];
      4'd15:
	  CASE_x524_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q13 =
	      naiveShfl_in[255:240];
    endcase
  end
  always@(x__h2590 or naiveShfl_in)
  begin
    case (x__h2590)
      4'd0:
	  CASE_x590_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q14 =
	      naiveShfl_in[15:0];
      4'd1:
	  CASE_x590_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q14 =
	      naiveShfl_in[31:16];
      4'd2:
	  CASE_x590_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q14 =
	      naiveShfl_in[47:32];
      4'd3:
	  CASE_x590_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q14 =
	      naiveShfl_in[63:48];
      4'd4:
	  CASE_x590_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q14 =
	      naiveShfl_in[79:64];
      4'd5:
	  CASE_x590_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q14 =
	      naiveShfl_in[95:80];
      4'd6:
	  CASE_x590_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q14 =
	      naiveShfl_in[111:96];
      4'd7:
	  CASE_x590_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q14 =
	      naiveShfl_in[127:112];
      4'd8:
	  CASE_x590_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q14 =
	      naiveShfl_in[143:128];
      4'd9:
	  CASE_x590_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q14 =
	      naiveShfl_in[159:144];
      4'd10:
	  CASE_x590_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q14 =
	      naiveShfl_in[175:160];
      4'd11:
	  CASE_x590_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q14 =
	      naiveShfl_in[191:176];
      4'd12:
	  CASE_x590_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q14 =
	      naiveShfl_in[207:192];
      4'd13:
	  CASE_x590_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q14 =
	      naiveShfl_in[223:208];
      4'd14:
	  CASE_x590_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q14 =
	      naiveShfl_in[239:224];
      4'd15:
	  CASE_x590_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q14 =
	      naiveShfl_in[255:240];
    endcase
  end
  always@(x__h2656 or naiveShfl_in)
  begin
    case (x__h2656)
      4'd0:
	  CASE_x656_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q15 =
	      naiveShfl_in[15:0];
      4'd1:
	  CASE_x656_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q15 =
	      naiveShfl_in[31:16];
      4'd2:
	  CASE_x656_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q15 =
	      naiveShfl_in[47:32];
      4'd3:
	  CASE_x656_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q15 =
	      naiveShfl_in[63:48];
      4'd4:
	  CASE_x656_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q15 =
	      naiveShfl_in[79:64];
      4'd5:
	  CASE_x656_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q15 =
	      naiveShfl_in[95:80];
      4'd6:
	  CASE_x656_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q15 =
	      naiveShfl_in[111:96];
      4'd7:
	  CASE_x656_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q15 =
	      naiveShfl_in[127:112];
      4'd8:
	  CASE_x656_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q15 =
	      naiveShfl_in[143:128];
      4'd9:
	  CASE_x656_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q15 =
	      naiveShfl_in[159:144];
      4'd10:
	  CASE_x656_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q15 =
	      naiveShfl_in[175:160];
      4'd11:
	  CASE_x656_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q15 =
	      naiveShfl_in[191:176];
      4'd12:
	  CASE_x656_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q15 =
	      naiveShfl_in[207:192];
      4'd13:
	  CASE_x656_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q15 =
	      naiveShfl_in[223:208];
      4'd14:
	  CASE_x656_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q15 =
	      naiveShfl_in[239:224];
      4'd15:
	  CASE_x656_0_naiveShfl_in_BITS_15_TO_0_1_naiveS_ETC__q15 =
	      naiveShfl_in[255:240];
    endcase
  end
  always@(naiveShfl_shftAmnt or naiveShfl_in)
  begin
    case (naiveShfl_shftAmnt)
      4'd0:
	  CASE_naiveShfl_shftAmnt_0_naiveShfl_in_BITS_15_ETC__q16 =
	      naiveShfl_in[15:0];
      4'd1:
	  CASE_naiveShfl_shftAmnt_0_naiveShfl_in_BITS_15_ETC__q16 =
	      naiveShfl_in[31:16];
      4'd2:
	  CASE_naiveShfl_shftAmnt_0_naiveShfl_in_BITS_15_ETC__q16 =
	      naiveShfl_in[47:32];
      4'd3:
	  CASE_naiveShfl_shftAmnt_0_naiveShfl_in_BITS_15_ETC__q16 =
	      naiveShfl_in[63:48];
      4'd4:
	  CASE_naiveShfl_shftAmnt_0_naiveShfl_in_BITS_15_ETC__q16 =
	      naiveShfl_in[79:64];
      4'd5:
	  CASE_naiveShfl_shftAmnt_0_naiveShfl_in_BITS_15_ETC__q16 =
	      naiveShfl_in[95:80];
      4'd6:
	  CASE_naiveShfl_shftAmnt_0_naiveShfl_in_BITS_15_ETC__q16 =
	      naiveShfl_in[111:96];
      4'd7:
	  CASE_naiveShfl_shftAmnt_0_naiveShfl_in_BITS_15_ETC__q16 =
	      naiveShfl_in[127:112];
      4'd8:
	  CASE_naiveShfl_shftAmnt_0_naiveShfl_in_BITS_15_ETC__q16 =
	      naiveShfl_in[143:128];
      4'd9:
	  CASE_naiveShfl_shftAmnt_0_naiveShfl_in_BITS_15_ETC__q16 =
	      naiveShfl_in[159:144];
      4'd10:
	  CASE_naiveShfl_shftAmnt_0_naiveShfl_in_BITS_15_ETC__q16 =
	      naiveShfl_in[175:160];
      4'd11:
	  CASE_naiveShfl_shftAmnt_0_naiveShfl_in_BITS_15_ETC__q16 =
	      naiveShfl_in[191:176];
      4'd12:
	  CASE_naiveShfl_shftAmnt_0_naiveShfl_in_BITS_15_ETC__q16 =
	      naiveShfl_in[207:192];
      4'd13:
	  CASE_naiveShfl_shftAmnt_0_naiveShfl_in_BITS_15_ETC__q16 =
	      naiveShfl_in[223:208];
      4'd14:
	  CASE_naiveShfl_shftAmnt_0_naiveShfl_in_BITS_15_ETC__q16 =
	      naiveShfl_in[239:224];
      4'd15:
	  CASE_naiveShfl_shftAmnt_0_naiveShfl_in_BITS_15_ETC__q16 =
	      naiveShfl_in[255:240];
    endcase
  end
endmodule  // module_naiveShfl

